trigger: none  # Entspricht 'workflow_dispatch'

name: Build-self-hosted-O64

pool:
  name: 'Self-hosted Runner'
  demands:
    - Agent.OS -equals Windows_NT

resources:
  repositories:
    - repository: msaccessVcsBuild
      type: github
      name: AccessCodeLib/msaccess-vcs-build
      ref: refs/heads/main
      endpoint: AccessCodeLib

steps:
  - checkout: self
    persistCredentials: true

  - task: PowerShell@2
    displayName: 'Build Access file (accdb/accde)'
    inputs:
      targetType: inline
      pwsh: true
      script: |
        # Starte das PowerShell-Skript direkt wie es in der Composite-Action gemacht wird
        $sourceDir = "source"
        $targetDir = ""
        $compile = $false
        $vcsUrl = "https://api.github.com/repos/josef-poetzl/msaccess-vcs-addin/releases/latest"

        $scriptPath = "/msaccess-vcs-build/Build.ps1"
        & $scriptPath -SourceDir $sourceDir -TargetDir $targetDir -Compile $compile -vcsUrl $vcsUrl
    timeoutInMinutes: 10

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Build Artifact'
    inputs:
      PathtoPublish: 'bin'
      ArtifactName: 'Binary files'
      publishLocation: 'Container'
