trigger: none  # Entspricht 'workflow_dispatch'

name: Build-self-hosted-O64

pool:
  name: 'Self-hosted Runner'
  demands:
    - Agent.OS -equals Windows_NT

resources:
  repositories:
    - repository: msaccess-vcs-build
      type: github
      name: AccessCodeLib/msaccess-vcs-build
      ref: refs/heads/main
      endpoint: AccessCodeLib

steps:
  - checkout: self
    persistCredentials: true
    
  - checkout: msaccess-vcs-build

  - task: PowerShell@2
    displayName: 'Build Access file (accdb/accde)'
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $sourceDir = "BuildAccdeExample\source"
        $targetDir = "bin"
        $compile = $false
        $vcsUrl = "https://api.github.com/repos/josef-poetzl/msaccess-vcs-addin/releases/latest"

        $scriptPath = "$(Build.SourcesDirectory)\msaccess-vcs-build\Build.ps1"
        Write-Host "Running script at $scriptPath"

        if (-Not (Test-Path $scriptPath)) {
          Write-Error "Build.ps1 not found at $scriptPath"
          exit 1
        }

        & $scriptPath -SourceDir $sourceDir -TargetDir $targetDir -Compile $compile -vcsUrl $vcsUrl

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Build Artifact'
    inputs:
      PathtoPublish: 'bin'
      ArtifactName: 'Binary files'
      publishLocation: 'Container'
