trigger: none

name: Build-self-hosted-MultiBit

resources:
  repositories:
    - repository: msaccess-vcs-build
      type: github
      name: AccessCodeLib/msaccess-vcs-build
      ref: refs/heads/main
      endpoint: AccessCodeLib

jobs:
- job: Build32bit
  displayName: 'Build 32-bit ACCDE'
  pool:
    name: 'Self-hosted Runner'
    demands:
      - Office-Bitness -equals 32
  steps:
    - checkout: self
      persistCredentials: true

    - checkout: msaccess-vcs-build

    - task: CmdLine@2
      displayName: 'Build 32-bit (32-bit PowerShell)'
      inputs:
        script: |
          "C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File "$(Build.SourcesDirectory)\msaccess-vcs-build\Build.ps1" -SourceDir "BuildAccdeExample\source" -TargetDir "bin32" -Compile "true" -AppConfigFile "BuildAccdeExample/deployment/Application-Config.json" -vcsUrl "https://api.github.com/repos/josef-poetzl/msaccess-vcs-addin/releases/latest"

    - task: PublishBuildArtifacts@1
      displayName: 'Publish 32-bit ACCDE'
      inputs:
        PathtoPublish: 'bin32'
        ArtifactName: 'ACCDE 32-bit'
        publishLocation: 'Container'

- job: Build64bit
  displayName: 'Build 64-bit ACCDE'
  pool:
    name: 'Self-hosted Runner'
    demands:
      - Office-Bitness -equals 64
  steps:
    - checkout: self
      persistCredentials: true

    - checkout: msaccess-vcs-build

    - task: PowerShell@2
      displayName: 'Build 64-bit'
      inputs:
        targetType: inline
        pwsh: true
        script: |
          $sourceDir = "BuildAccdeExample\source"
          $targetDir = "bin64"
          $compile = "true"
          $appConfig = "BuildAccdeExample/deployment/Application-Config.json"
          $vcsUrl = "https://api.github.com/repos/josef-poetzl/msaccess-vcs-addin/releases/latest"

          & "$(Build.SourcesDirectory)\msaccess-vcs-build\Build.ps1" -SourceDir $sourceDir -TargetDir $targetDir -Compile $compile -AppConfigFile "$appConfig" -vcsUrl $vcsUrl

    - task: PublishBuildArtifacts@1
      displayName: 'Publish 64-bit ACCDE'
      inputs:
        PathtoPublish: 'bin64'
        ArtifactName: 'ACCDE 64-bit'
        publishLocation: 'Container'
