name: Build-self-hosted
on:
  - workflow_dispatch

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }} 
      - name: "Build Access file (accdb/accde)"
        id: build_access_file
        uses: AccessCodeLib/msaccess-vcs-build@main
        with:
          source-dir: "./source"
          target-dir: "bin"
          compile: true
          vcs-url: "https://api.github.com/repos/josef-poetzl/msaccess-vcs-addin/releases/latest"
        timeout-minutes: 10
      - name: "Upload Build Artifact"
        uses: actions/upload-artifact@v4
        id: "upload"
        with:
          name: "Binary files"
          path: "./bin/*"
          if-no-files-found: warn
      - name: "Attestation"
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "Binary files"
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
